name: Issue Report
description: File an issue report
title: "[Issue]: "
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as necessary.
  - type: textarea
    id: what-happened
    attributes:
      label: Please describe your bug
      description: Also tell us, what did you expect to happen?
      placeholder: |
        The more information that you are able to provide, the better. Did you do anything before this happened? Any screenshots or logs you can provide will be helpful.

        This is my issue.

        Steps to Reproduce
          1. ...
          2. ...
          3. ...
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Jellyflix Version
      description: What version of Jellyflix are you running?
      options:
        - 0.9.13
        - 0.10.x
        - 0.11.x
        - 0.12.x
        - Other
    validations:
      required: true
  - type: input
    id: version-other
    attributes:
      label: "if other:"
      placeholder: Other
  - type: dropdown
    id: jellyfin-version
    attributes:
      label: Jellyfin Version
      description: What version of Jellyfin are you running?
      options:
        - 10.8.13
        - 10.9.x
        - Other
    validations:
      required: true
  - type: input
    id: jellyfin-version-other
    attributes:
      label: "if other:"
      placeholder: Other
  - type: textarea
    attributes:
      label: Environment
      description: |
        Examples:
        - **OS**: [iOS, Android, macOS, Windows, Linux]
        - **OS Version**: [iOS 17.3, Android 12, macOS 14, Windows 10, Ubuntu 18.04 etc.]
        - **Playback**: [Direct Play, Remux, Direct Stream, Transcode]
      value: |
        - OS:
        - OS Version:
        - Playback Method:
      render: markdown
    
